config/routes.rb
# -*- encoding : utf-8 -*-
Clinics::Application.routes.draw do
  resources :pacientes

  resources :convenios

  resources :terapeutas

  root :to => 'home#index'
end

app/models/convenio.rb
# -*- encoding : utf-8 -*-
class Convenio < ActiveRecord::Base
	validates_presence_of :nome, :message => "é necessário."
end

app/models/paciente.rb
# -*- encoding : utf-8 -*-
class Paciente < ActiveRecord::Base
end

app/models/terapeuta.rb
# -*- encoding : utf-8 -*-
class Terapeuta < ActiveRecord::Base
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/convenios_controller.rb
# -*- encoding : utf-8 -*-
class ConveniosController < InheritedResources::Base
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pacientes_controller.rb
# -*- encoding : utf-8 -*-
class PacientesController < InheritedResources::Base
end

app/controllers/terapeutas_controller.rb
# -*- encoding : utf-8 -*-
class TerapeutasController < InheritedResources::Base
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/convenios_helper.rb
# -*- encoding : utf-8 -*-
module ConveniosHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/pacientes_helper.rb
# -*- encoding : utf-8 -*-
module PacientesHelper
end

app/helpers/terapeutas_helper.rb
# -*- encoding : utf-8 -*-
module TerapeutasHelper
end

app/views/convenios/_form.html.erb
<%= form_for(@convenio) do |f| %>
  <% if @convenio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@convenio.errors.count, "erro impediu") %> o convênio de ser salvo:</h2>

      <ul>
      <% @convenio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar Paciente", :class => "btn-success" %>
  </div>
<% end %>

app/views/convenios/edit.html.erb
<h1>Editando convênio</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @convenio %> |
<%= link_to 'Voltar', convenios_path %>

app/views/convenios/index.html.erb
<h1>Listando convênios</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @convenios.each do |convenio| %>
  <tr>
    <td><%= convenio.nome %></td>
    <td><%= link_to 'Exibir', convenio %></td>
    <td><%= link_to 'Editar', edit_convenio_path(convenio) %></td>
    <td><%= link_to 'Deletar', convenio, :confirm => 'Tem certeza?', :class => "btn-danger", :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Convênio', new_convenio_path %>

app/views/convenios/new.html.erb
<h1>Novo convênio</h1>

<%= render 'form' %>

<%= link_to 'Voltar', convenios_path %>

app/views/convenios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @convenio.nome %>
</p>


<%= link_to 'Editar', edit_convenio_path(@convenio) %> |
<%= link_to 'Voltar', convenios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clinics</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to 'Clinics', '/', :class => "brand" %>

				<ul class="nav">
					<li><%= link_to 'Convenios', convenios_path %></li>
					<li><%= link_to 'Pacientes', pacientes_path %></li>
					<li><%= link_to 'Terapeutas', terapeutas_path %></li>
				</ul>
			</div>
  		</div>
  </div>

  <%= yield %>

</body>
</html>

app/views/pacientes/_form.html.erb
<%= form_for(@paciente) do |f| %>
  <% if @paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paciente.errors.count, "error") %> impediu este paciente de ser salvo:</h2>

      <ul>
      <% @paciente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :bairro %><br />
    <%= f.text_field :bairro %>
  </div>
  <div class="field">
    <%= f.label :cep %><br />
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :celular %><br />
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :data_de_nascimento %><br />
    <%= f.date_select :data_de_nascimento %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :nome_da_mae %><br />
    <%= f.text_field :nome_da_mae %>
  </div>
  <div class="field">
    <%= f.label :nome_do_pai %><br />
    <%= f.text_field :nome_do_pai %>
  </div>
  <div class="field">
    <%= f.label :convenio %><br />
    <%= f.text_field :convenio %>
  </div>
  <div class="field">
    <%= f.label :valor_parficular %><br />
    <%= f.text_field :valor_parficular %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cid %><br />
    <%= f.text_field :cid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editando paciente</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @paciente %> |
<%= link_to 'Voltar', pacientes_path %>

app/views/pacientes/index.html.erb
<h1>Listando pacientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
    <th>Bairro</th>
    <th>CEP</th>
    <th>Telefone</th>
    <th>Celular</th>
    <th>Data de nascimento</th>
    <th>Sexo</th>
    <th>Nome da mae</th>
    <th>Nome do pai</th>
    <th>Convênio</th>
    <th>Valor parficular</th>
    <th>E-mail</th>
    <th>CID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pacientes.each do |paciente| %>
  <tr>
    <td><%= paciente.nome %></td>
    <td><%= paciente.endereco %></td>
    <td><%= paciente.bairro %></td>
    <td><%= paciente.cep %></td>
    <td><%= paciente.telefone %></td>
    <td><%= paciente.celular %></td>
    <td><%= paciente.data_de_nascimento %></td>
    <td><%= paciente.sexo %></td>
    <td><%= paciente.nome_da_mae %></td>
    <td><%= paciente.nome_do_pai %></td>
    <td><%= paciente.convenio %></td>
    <td><%= paciente.valor_parficular %></td>
    <td><%= paciente.email %></td>
    <td><%= paciente.cid %></td>
    <td><%= link_to 'Exibir', paciente %></td>
    <td><%= link_to 'Editar', edit_paciente_path(paciente) %></td>
    <td><%= link_to 'Deletar', paciente, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>Novo paciente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @paciente.nome %>
</p>

<p>
  <b>Endereco:</b>
  <%= @paciente.endereco %>
</p>

<p>
  <b>Bairro:</b>
  <%= @paciente.bairro %>
</p>

<p>
  <b>CEP:</b>
  <%= @paciente.cep %>
</p>

<p>
  <b>Telefone:</b>
  <%= @paciente.telefone %>
</p>

<p>
  <b>Celular:</b>
  <%= @paciente.celular %>
</p>

<p>
  <b>Data de nascimento:</b>
  <%= @paciente.data_de_nascimento %>
</p>

<p>
  <b>Sexo:</b>
  <%= @paciente.sexo %>
</p>

<p>
  <b>Nome da mae:</b>
  <%= @paciente.nome_da_mae %>
</p>

<p>
  <b>Nome do pai:</b>
  <%= @paciente.nome_do_pai %>
</p>

<p>
  <b>Convenio:</b>
  <%= @paciente.convenio %>
</p>

<p>
  <b>Valor parficular:</b>
  <%= @paciente.valor_parficular %>
</p>

<p>
  <b>E-mail:</b>
  <%= @paciente.email %>
</p>

<p>
  <b>CID:</b>
  <%= @paciente.cid %>
</p>


<%= link_to 'Editar', edit_paciente_path(@paciente) %> |
<%= link_to 'Voltar', pacientes_path %>

app/views/terapeutas/_form.html.erb
<%= form_for(@terapeuta) do |f| %>
  <% if @terapeuta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@terapeuta.errors.count, "error") %> impediram este terapeuta de ser salvo:</h2>

      <ul>
      <% @terapeuta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :crp %><br />
    <%= f.text_field :crp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terapeutas/edit.html.erb
<h1>Editando terapeuta</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @terapeuta %> |
<%= link_to 'Voltar', terapeutas_path %>

app/views/terapeutas/index.html.erb
<h1>Listando terapeutas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>CRP</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @terapeutas.each do |terapeuta| %>
  <tr>
    <td><%= terapeuta.nome %></td>
    <td><%= terapeuta.crp %></td>
    <td><%= link_to 'Exibir', terapeuta %></td>
    <td><%= link_to 'Editar', edit_terapeuta_path(terapeuta) %></td>
    <td><%= link_to 'Deletar', terapeuta, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Terapeuta', new_terapeuta_path %>

app/views/terapeutas/new.html.erb
<h1>Novo terapeuta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', terapeutas_path %>

app/views/terapeutas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @terapeuta.nome %>
</p>

<p>
  <b>Crp:</b>
  <%= @terapeuta.crp %>
</p>


<%= link_to 'Editar', edit_terapeuta_path(@terapeuta) %> |
<%= link_to 'Voltar', terapeutas_path %>